# Generated by Django 4.0.5 on 2022-06-22 21:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 21, 59, 5, 439254, tzinfo=utc)),
        ),
    ]
